version: "3.7"
services:
  postgres:
    image: postgres:14
    profiles: ["standalone"]
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    profiles: ["standalone", "prod"]
    container_name: redis
    restart: always
    env_file:
      - .env.prod
    volumes:
      - redis:/data

  node:
    build:
      context: .
      dockerfile: Dockerfile
    profiles: ["standalone", "prod"]
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.prod

volumes:
  postgres:
    name: arabot-db
  redis:
    name: arabot-redis
