services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    env_file:
      - .env
    volumes:
      - redis:/data

  node:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  postgres:
    name: arabot-db
  redis:
    name: arabot-redis
