version: "3.7"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - arabot
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    env_file:
      - .env
    volumes:
      - redis:/data
    networks:
      - arabot
    ports:
      - "6379:6379"

  arabot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arabot
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - arabot

volumes:
  postgres:
    name: arabot-db
  redis:
    name: arabot-redis

networks:
  arabot: